In [1]:
import numpy as np

In [3]:
train_data = np.load('./datasets/train/binance_dataset_2021-02-07_2377073425.npy')

In [4]:
train_data.shape

(68875, 41)

In [6]:
train_data

array([[4.27760e-02, 4.27330e-02, 9.85010e+01, ..., 1.34920e+01,
        4.32040e-02, 1.83207e+02],
       [4.28160e-02, 4.27510e-02, 8.60660e+01, ..., 4.91867e+02,
        4.32220e-02, 2.29363e+02],
       [4.27980e-02, 4.27550e-02, 9.31350e+01, ..., 4.91342e+02,
        4.32260e-02, 2.20629e+02],
       ...,
       [4.13290e-02, 4.12880e-02, 3.10762e+02, ..., 1.30030e+01,
        4.17420e-02, 4.11950e+01],
       [4.13250e-02, 4.12830e-02, 2.90226e+02, ..., 1.30470e+01,
        4.17370e-02, 9.12580e+01],
       [4.13250e-02, 4.12830e-02, 2.94834e+02, ..., 1.30470e+01,
        4.17370e-02, 9.12580e+01]])

In [21]:
a = np.array([[1,2,3,5,7], [1,4,5,6,7],[5,8,9,10,32],[3,5,6,13,11]])
a

array([[ 1,  2,  3,  5,  7],
       [ 1,  4,  5,  6,  7],
       [ 5,  8,  9, 10, 32],
       [ 3,  5,  6, 13, 11]])

In [32]:
offset = 2
np.diff(a,offset) / a[:,offset:]

array([[ 0.        ,  0.2       ,  0.        ],
       [-0.4       ,  0.        ,  0.        ],
       [-0.22222222,  0.        ,  0.65625   ],
       [-0.16666667,  0.46153846, -0.81818182]])

In [34]:
d =2
a[d:] - a[:-d]

array([[ 4,  6,  6,  5, 25],
       [ 2,  1,  1,  7,  4]])

In [53]:
a[0:3,:]

array([[ 1,  2,  3,  5,  7],
       [ 1,  4,  5,  6,  7],
       [ 5,  8,  9, 10, 32]])